###
POST http://localhost:3000/api/teams HTTP/1.1
Content-Type: application/json

{
    "name": "RedBull Racing ",
    "foundation": 2005,
    "victories": 89,
    "championshipswins": 5,
    "lastdriver1": "Max Verstappen",
    "lastdriver2": "Sergio Pérez"
}

###
GET http://localhost:3000/api/teams HTTP/1.1

###
GET http://localhost:3000/api/teams/6369611ec70db2904fddda22 HTTP/1.1 
###
PUT http://localhost:3000/api/teams/6369611ec70db2904fddda22 HTTP/1.1
Content-Type: application/json

{
    "name": "RedBull Racing ",
    "foundation": 2005,
    "victories": 89,
    "championshipswins": 5,
    "lastdriver1": "Max Verstappen",
    "lastdriver2": "Sergio Pérez"
} 

###
DELETE http://localhost:3000/api/teams/636ab06d43aaf0aa76a87d1e HTTP/1.1